#
# under: trilobite devops:
# author: Michael Gene Ridge Brockus
# gmail: <michaelbrockus@gmail.com>
#
name: Host MacOSX CI

#
# We have is configured so that ci_runner_macosx only runs
# when source files, build scripts and this CI files is
# changed, we should not just run CI for all changes.
#
on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.txt"
      - "**.build"
  pull_request:
    branches:
      - "main"
      - "next"
    paths:
      - "**.c"
      - "**.h"
      - "**.txt"
      - "**.build"

permissions:
  contents: read

#
# We list all the Mac OSX systems in a nice list so the
# DevOps team can manage them.
# 
jobs:
  #
  # Mac OSX latest host system target
  #
  host_macosx_latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          brew install cppcheck
    - name: Setup Trilo Project
      run: |
           scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Trilo Project
      run: |
           cppcheck --project=builddir/compile_commands.json
    - name: Compile Trilo Project
      run: |
           scan-build meson compile -C builddir -v
    - name: Test Trilo Project
      run: |
           scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOSX_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Mac OSX 11 host system target
  #
  host_macosx_11:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          brew install cppcheck
    - name: Setup Trilo Project
      run: |
           scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Trilo Project
      run: |
           cppcheck --project=builddir/compile_commands.json
    - name: Compile Trilo Project
      run: |
           scan-build meson compile -C builddir -v
    - name: Test Trilo Project
      run: |
           scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOSX_11_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

  #
  # Mac OSX 12 host system target
  #
  host_macosx_12:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Meson Build
      run: |
          pip install meson==1.0.0 ninja==1.11.1 scan-build
          brew install cppcheck
    - name: Setup Trilo Project
      run: |
           scan-build meson setup builddir -Dwith_tests=enabled
    - name: Scan Trilo Project
      run: |
           cppcheck --project=builddir/compile_commands.json
    - name: Compile Trilo Project
      run: |
           scan-build meson compile -C builddir -v
    - name: Test Trilo Project
      run: |
           scan-build meson test -C builddir -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOSX_12_Meson_Testlog
        path: builddir/meson-logs/testlog.txt
